name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Clone repository manually
      run: |
        git clone https://github.com/${{ github.repository }}.git .
        git checkout main

    - name: Set up Java
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
        java -version

    - name: Set up Flutter SDK
      run: |
        git clone https://github.com/flutter/flutter.git -b 3.19.0 --depth 1 _flutter
        echo "$GITHUB_WORKSPACE/_flutter/bin" >> $GITHUB_PATH

    - name: Doctor and config
      run: |
        flutter doctor
        flutter config --no-analytics

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
